server:
  port: 8084

spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: battle

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

pokemon-factory:
  assets:
    image-base-url: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites

logging:
  level:
    org.mybatis: info
    com.baomidou: info
