/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BattleActionPanel: typeof import('./src/components/BattleActionPanel.vue')['default']
    BattleArena: typeof import('./src/components/BattleArena.vue')['default']
    BattleDecisionPanel: typeof import('./src/components/BattleDecisionPanel.vue')['default']
    BattleHeaderPanel: typeof import('./src/components/BattleHeaderPanel.vue')['default']
    BattleLeaderboardModal: typeof import('./src/components/BattleLeaderboardModal.vue')['default']
    BattleSettlementModal: typeof import('./src/components/BattleSettlementModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ErrorHandler: typeof import('./src/components/ErrorHandler.vue')['default']
    EvolutionChainPanel: typeof import('./src/components/EvolutionChainPanel.vue')['default']
    EvolutionTreeNode: typeof import('./src/components/EvolutionTreeNode.vue')['default']
    ExchangeModal: typeof import('./src/components/ExchangeModal.vue')['default']
    GlobalLoader: typeof import('./src/components/GlobalLoader.vue')['default']
    PokemonAbilitiesPanel: typeof import('./src/components/PokemonAbilitiesPanel.vue')['default']
    PokemonCardGrid: typeof import('./src/components/PokemonCardGrid.vue')['default']
    PokemonCompareModal: typeof import('./src/components/PokemonCompareModal.vue')['default']
    PokemonHeaderDetail: typeof import('./src/components/PokemonHeaderDetail.vue')['default']
    PokemonMovesPanel: typeof import('./src/components/PokemonMovesPanel.vue')['default']
    PokemonSearchFilters: typeof import('./src/components/PokemonSearchFilters.vue')['default']
    PokemonStatsCard: typeof import('./src/components/PokemonStatsCard.vue')['default']
    PokemonStatsPanel: typeof import('./src/components/PokemonStatsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
