/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BanModal: typeof import('./src/components/BanModal.vue')['default']
    BattleLeaderboardModal: typeof import('./src/components/BattleLeaderboardModal.vue')['default']
    BattleSettlementModal: typeof import('./src/components/BattleSettlementModal.vue')['default']
    CatalogPageHeader: typeof import('./src/components/CatalogPageHeader.vue')['default']
    CatalogSkeleton: typeof import('./src/components/CatalogSkeleton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EvolutionChainPanel: typeof import('./src/components/EvolutionChainPanel.vue')['default']
    ExchangeModal: typeof import('./src/components/ExchangeModal.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    ItemDetailDialog: typeof import('./src/components/ItemDetailDialog.vue')['default']
    LoadMoreTrigger: typeof import('./src/components/LoadMoreTrigger.vue')['default']
    MoveDetailDialog: typeof import('./src/components/MoveDetailDialog.vue')['default']
    PokemonAbilitiesPanel: typeof import('./src/components/PokemonAbilitiesPanel.vue')['default']
    PokemonCalcPanel: typeof import('./src/components/PokemonCalcPanel.vue')['default']
    PokemonCardGrid: typeof import('./src/components/PokemonCardGrid.vue')['default']
    PokemonCompareModal: typeof import('./src/components/PokemonCompareModal.vue')['default']
    PokemonDetailPopover: typeof import('./src/components/PokemonDetailPopover.vue')['default']
    PokemonHeaderDetail: typeof import('./src/components/PokemonHeaderDetail.vue')['default']
    PokemonMovesPanel: typeof import('./src/components/PokemonMovesPanel.vue')['default']
    PokemonSearchFilters: typeof import('./src/components/PokemonSearchFilters.vue')['default']
    PokemonStatsCard: typeof import('./src/components/PokemonStatsCard.vue')['default']
    PokemonStatsPanel: typeof import('./src/components/PokemonStatsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
