/**
 * 对战常用道具效果中文翻译
 * =========================
 * 后端 PokeAPI 缓存仅提供英文效果（item effect_entries 无 zh-Hans），
 * 这里为前端展示提供常用对战道具的中文翻译，未收录的道具回退英文原文。
 */
export const ITEM_EFFECT_ZH = {
  'assault-vest': '携带后特防提升至 1.5 倍，但无法使用变化招式。',
  'life-orb': '招式威力提升 30%，但每次攻击会损失最大 HP 的 10%。',
  'choice-band': '攻击提升 50%，但只能使用选择的第一个招式。',
  'choice-specs': '特攻提升 50%，但只能使用选择的第一个招式。',
  'choice-scarf': '速度提升 50%，但只能使用选择的第一个招式。',
  'focus-sash': '满 HP 时受到致命一击会保留 1 点 HP。',
  'leftovers': '每回合结束时恢复最大 HP 的 1/16。',
  'rocky-helmet': '受到接触类招式攻击时，攻击者损失最大 HP 的 1/6。',
  'eviolite': '未完全进化的宝可梦携带时，防御与特防提升 1.5 倍。',
  'heavy-duty-boots': '不会受到场地陷阱（撒菱、隐形岩等）的伤害。',
  'safety-goggles': '免疫粉末类招式与沙暴天气的伤害。',
  'air-balloon': '不会受到地面属性招式的攻击（气球被打碎前）。',
  'black-sludge': '毒属性宝可梦每回合恢复最大 HP 的 1/16，其他属性则损失。',
  'terrain-extender': '场地的效果延长至 8 回合。',
  'light-clay': '光墙与反射壁的效果延长至 8 回合。',
  'expert-belt': '招式效果绝佳时，伤害提升 20%。',
  'muscle-band': '物理招式威力提升 10%。',
  'wise-glasses': '特殊招式威力提升 10%。',
  'weakness-policy': '受到效果绝佳的招式攻击时，攻击与特攻提升 2 级。',
  'life-orb-copy': '',
  'red-card': '受到攻击时，强制攻击者替换下场。',
  'eject-button': '受到攻击时，立即替换下场。',
  'custap-berry': 'HP 低于 1/4 时，本回合先出手。',
  'sitrus-berry': 'HP 低于 1/2 时，恢复最大 HP 的 1/4。',
  'iapapa-berry': 'HP 低于 1/4 时，恢复最大 HP 的 1/3。',
  'figy-berry': 'HP 低于 1/4 时，恢复最大 HP 的 1/3。',
  'aguav-berry': 'HP 低于 1/4 时，恢复最大 HP 的 1/3。',
  'wik-berry': 'HP 低于 1/4 时，恢复最大 HP 的 1/3。',
  'mago-berry': 'HP 低于 1/4 时，恢复最大 HP 的 1/3。',
  'lum-berry': '解除所有异常状态。',
  'chesto-berry': '解除睡眠状态。',
  'rawst-berry': '解除灼伤状态。',
  'aspear-berry': '解除冰冻状态。',
  'pecha-berry': '解除中毒状态。',
  'persim-berry': '解除混乱状态。',
  'cheri-berry': '解除麻痹状态。',
  'mental-herb': '解除挑衅、嘲讽等妨碍状态。',
  'power-herb': '无需等待蓄力回合即可使用蓄力招式。',
  'white-herb': '能力下降时恢复原状。',
  'absorb-bulb': '受到水属性招式攻击时，特攻提升 1 级。',
  'cell-battery': '受到电属性招式攻击时，攻击提升 1 级。',
  'snowball': '受到冰属性招式攻击时，攻击提升 1 级。',
  'luminous-moss': '受到水属性招式攻击时，特防提升 1 级。',
  'ability-shield': '不会受到特性被消除或被复制的影响。',
  'clear-amulet': '不会受到能力下降的影响。',
  'covert-cloak': '不会受到招式附加效果的影响。',
  'loaded-dice': '连续攻击类招式至少命中 4 次。',
  'punching-glove': '拳类招式威力提升 10%，且不会触发接触效果。',
  'throat-spray': '使用声音类招式后，特攻提升 1 级。',
  'utility-umbrella': '不受雨天与晴天的效果影响。',
  'ring-target': '所有招式都能命中（包括免疫的属性）。',
  'room-service': '戏法空间生效时速度下降，且不受空间减速影响。',
  'blunder-policy': '招式落空时，速度提升 2 级。',
  'scope-lens': '击中要害的概率提升 1 级。',
  'razor-claw': '击中要害的概率提升 1 级。',
  'bright-powder': '降低对手招式的命中率。',
  'lax-incense': '降低对手招式的命中率。',
  'quick-claw': '每回合有 20% 概率先出手。',
  'king-s-rock': '攻击招式有 10% 概率使对手畏缩。',
  'razor-fang': '攻击招式有 10% 概率使对手畏缩。',
  'flame-orb': '回合结束时灼伤携带者。',
  'toxic-orb': '回合结束时使携带者剧毒。',
  'sticky-barb': '接触时粘在攻击者身上并使其损失 HP。',
  'iron-ball': '速度减半且变为地面属性（可被地面招式命中）。',
  'lagging-tail': '最后出手。',
  'full-incense': '最后出手。',
  'choice-scarf-copy': '',
  'normalium-z': '一般属性招式升级为 Z 招式。',
  'focus-band': '有 10% 概率承受致命一击。',
  'shed-shell': '不受捆绑类招式影响，且必定能替换下场。',
  'safety-goggles-copy': ''
}

/** 获取道具效果中文（未收录时返回英文原文或空串） */
export function itemEffectZh(effectEn, nameEn) {
  if (!nameEn) return effectEn || ''
  return ITEM_EFFECT_ZH[nameEn] || effectEn || ''
}
